hw09_struct_validator
avilov-dmitry/golang_otus_home_work pull request #9
Opened 2022-09-29 21:01 UTC by avilov-dmitry

2022-10-30 17:35 UTC, dshemin requested changes

2022-10-30 17:35 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	if v.Err == nil {
Тут не совсем понятна логика. Если это ошибка, то тут должен быть err всегда.

2022-10-30 17:35 UTC, dshemin commented on hw09_struct_validator/validator.go
> +func hasValidationErrors(ve ValidationErrors) bool {
Это можно сделать методом `ValidationErrors`.

2022-10-30 17:35 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	var ok bool
Код слишком сложный. Будет проще сделать так: если мы смогли найти значение в массиве, сразу вернуть nil.

2022-10-30 17:35 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	var ok bool
Тут тоже можно сразу вернуть nil, если нашли элемент.

2022-10-30 17:35 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		sliceElem := sliceVal.Index(i)
Код внутри цикла очень сильно напоминает код в validateSingle. Попробуйте переиспользовать.

2022-10-30 17:35 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	err := doValidateValue(kind, field, ruleName, ruleValStr)
Можно сразу `return doValidateValue(...)`

2022-11-01 19:18 UTC, avilov-dmitry commented on hw09_struct_validator/validator.go
> +	if v.Err == nil {
поправил

2022-11-01 19:19 UTC, avilov-dmitry commented on hw09_struct_validator/validator.go
> +func hasValidationErrors(ve ValidationErrors) bool {
Удалил этот метод

2022-11-01 19:19 UTC, avilov-dmitry commented on hw09_struct_validator/validator.go
> +	var ok bool
поправил

2022-11-01 19:20 UTC, avilov-dmitry commented on hw09_struct_validator/validator.go
> +	err := doValidateValue(kind, field, ruleName, ruleValStr)
поправил

2022-11-01 19:21 UTC, avilov-dmitry commented on hw09_struct_validator/validator.go
> +	var ok bool
поправил

2022-11-01 19:55 UTC, avilov-dmitry commented on hw09_struct_validator/validator.go
> +		sliceElem := sliceVal.Index(i)
добрый вечер, у меня не получилось, тк validateSingle принимает другие параметры на вход

2022-11-02 01:20 UTC, dshemin approved these changes

2022-11-02 03:14 UTC, avilov-dmitry commented
Доброе утро, примите, пожалуйста, инвайт в этот репозиторий, чтобы я смог смержить ветку

2022-11-02 03:21 UTC, dshemin commented
Принял

2022-11-02 18:49 UTC, merged